{% set version = "1.8.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-loader
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/loadeR/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7496a4de8b66d93778e054ba19edd31db01ac63cdec66dc078f01264074d3e67

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcurl
    - r-abind
    - r-climate4r.udg >=0.2.0
    - r-loader.java
    - r-rjava
  run:
    - r-base
    - r-rcurl
    - r-abind
    - r-climate4r.udg >=0.2.0
    - r-loader.java
    - r-rjava

test:
  commands:
    - $R -e "library('loadeR')"           # [not win]
    - "\"%R%\" -e \"library('loadeR')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/climate4R
  license: GPL-3.0-or-later
  summary: Enables harmonized access to either remote climate databases via OPeNDAP or to locally stored data, allowing the retrieval of user-defined dimensional slices from large climate datasets. For more details see Iturbide et al 2019 <http://dx.doi.org/10.1016/j.envsoft.2018.09.009>.
  doc_url: https://github.com/SantanderMetGroup/loadeR/wiki
  dev_url: https://github.com/SantanderMetGroup/loadeR
  license_family: GPL3
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa
